import React from 'react';
import { Inter } from 'next/font/google';
import Link from 'next/link';
import './globals.css';
import { FaHome } from 'react-icons/fa';
import { IoEarth } from 'react-icons/io5';
import { CiCirclePlus } from 'react-icons/ci';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<nav>
					<ul>
						<li style={{ pointerEvents: 'none' }}>
							<Link href='/'>home</Link>
						</li>
						<li style={{ pointerEvents: 'none' }}>
							<Link href='/tours'>tours</Link>
						</li>
						<li style={{ pointerEvents: 'none' }}>
							<Link href='/create'>create</Link>
						</li>
						{/* Add the anchor tags here */}
						<li>
							<a href='/' className='home-button'>
								<FaHome className='icon home' />
							</a>
						</li>
						<li>
							<a href='/tours' className='itinerary-button'>
								<CiCirclePlus className='icon itinerary' />
							</a>
						</li>
						<li>
							<a href='/create' className='browse-button'>
								<IoEarth className='browse icon' />
							</a>
						</li>
					</ul>
				</nav>
				{children}
			</body>
		</html>
	);
}
